export const STORAGE_KEYS = {
  theme: 'sportstock_theme',
  settings: 'sportstock_settings',
  inventory: 'sportstock_inventory',
  transactions: 'sportstock_transactions',
};

export const createDefaultStoreSettings = () => ({
  name: 'NIL Sports',
  address: '123, Stadium Road, Kolhapur',
  phone: '+91 98765 43210',
  currency: '\u20b9',
  defaultMinStock: 5,
  gstin: '',
  taxRate: 0,
});

export const createDefaultInventory = () => ([
  {
    id: 1,
    name: 'SG English Willow Bat',
    category: 'Cricket',
    brand: 'SG',
    price: 8500,
    costPrice: 6000,
    size: 'SH',
    stock: 12,
    minLevel: 5,
    description: 'Premium Grade 1 English Willow for professional play.',
    image: null,
  },
  {
    id: 2,
    name: 'Nivia Shining Star Football',
    category: 'Football',
    brand: 'Nivia',
    price: 950,
    costPrice: 650,
    size: '5',
    stock: 24,
    minLevel: 10,
    description: 'Durable rubberized stitched football for hard grounds.',
    image: null,
  },
  {
    id: 3,
    name: 'Yonex Muscle Power Racket',
    category: 'Tennis',
    brand: 'Yonex',
    price: 3200,
    costPrice: 2100,
    size: 'G4',
    stock: 4,
    minLevel: 5,
    description: 'High repulsion power and sharp shots.',
    image: null,
  },
  {
    id: 4,
    name: 'Adidas Team India Jersey',
    category: 'Apparel',
    brand: 'Adidas',
    price: 4999,
    costPrice: 3500,
    size: 'L',
    stock: 15,
    minLevel: 5,
    description: 'Official Team India ODI Jersey 2023.',
    image: null,
  },
  {
    id: 5,
    name: 'Dumbbell Set (5kg)',
    category: 'Gym',
    brand: 'Decathlon',
    price: 1500,
    costPrice: 900,
    size: '5kg',
    stock: 8,
    minLevel: 5,
    description: 'Vinyl coated cast iron dumbbells.',
    image: null,
  },
]);

export const createDefaultTransactions = () => ([
  {
    id: 101,
    date: new Date().toISOString(),
    type: 'SALE',
    amount: 8500,
    profit: 2500,
    description: 'Sale: SG English Willow Bat',
  },
  {
    id: 102,
    date: new Date().toISOString(),
    type: 'SALE',
    amount: 1900,
    profit: 600,
    description: 'Sale: 2x Nivia Football',
  },
  {
    id: 103,
    date: new Date().toISOString(),
    type: 'SALE',
    amount: 3200,
    profit: 1100,
    description: 'Sale: Yonex Racket',
  },
  {
    id: 99,
    date: '2023-11-15T10:00:00.000Z',
    type: 'SALE',
    amount: 15000,
    profit: 5000,
    description: 'Old Sale: Kit',
  },
  {
    id: 98,
    date: '2023-05-20T10:00:00.000Z',
    type: 'SALE',
    amount: 8000,
    profit: 2000,
    description: 'Old Sale: Bats',
  },
]);

export const createDefaultNewItem = () => ({
  name: '',
  category: 'Cricket',
  brand: '',
  price: '',
  costPrice: '',
  size: '',
  stock: '',
  description: '',
  image: null,
});

export const createDefaultAppState = () => ({
  isDarkMode: false,
  storeSettings: createDefaultStoreSettings(),
  inventory: createDefaultInventory(),
  transactions: createDefaultTransactions(),
});
